### ISSUE TITLE
Unable to format dbt snowflake sql file

### ISSUE THREAD

**Issue by coleheflin-gt** [sqlfluff/sqlfluff#5325]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I was attempting to run the fix command on a snowflake dbt sql file and was receiving the following error:

```
> WARNING    One fix for LT01 not applied, it would re-cause the same error.
> WARNING    One fix for LT01 not applied, it would re-cause the same error.
> WARNING    One fix for LT01 not applied, it would re-cause the same error.
> WARNING    One fix for LT01 not applied, it would re-cause the same error.
> WARNING    One fix for LT01 not applied, it would re-cause the same error.
> WARNING    One fix for LT01 not applied, it would re-cause the same error.
> WARNING    Loop limit on fixes reached [10].
> ==== no fixable linting violations found ====
```

### Expected Behaviour

I was expecting to have the file get formatted properly but instead it said it found 26 unfixable linting violations.

### Observed Behaviour

After I ran the command, `sqlfluff fix test.sql`, I received the below error:

```
==== finding fixable violations ====
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
WARNING    One fix for LT01 not applied, it would re-cause the same error.
WARNING    One fix for LT01 not applied, it would re-cause the same error.
WARNING    One fix for LT01 not applied, it would re-cause the same error.
WARNING    One fix for LT01 not applied, it would re-cause the same error.
WARNING    One fix for LT01 not applied, it would re-cause the same error.
WARNING    One fix for LT01 not applied, it would re-cause the same error.
WARNING    Loop limit on fixes reached [10].
==== no fixable linting violations found ====
All Finished 📜 🎉!
  [26 unfixable linting violations found]
```

### How to reproduce

Here is the SQL file:
```
{{
    config(
        materialized='incremental',
        unique_key="id",
        schema="public",
    )
}}

WITH monthly_purchases AS (
    SELECT 
        YEAR("DATE") AS YEAR
        , MONTH("DATE") AS MONTH
        , PLATFORM
        , ID
        , EXAMPLE_ID
        , IS_MOBILE
        , SUM(CASE WHEN EVENT_NAME = 'purchase' THEN 1 ELSE 0 END) AS NUM_PURCHASES
        -- , sum(case when event_name = 'view' then 1 else 0 end) as view_cnt
    FROM {{ source('public', 'test') }} test
    {% if is_incremental() %}
    WHERE "DATE" >= DATEADD(DAY, -28, CURRENT_DATE)
    {% endif %}
    GROUP BY ALL
)
SELECT 
    {{ dbt_utils.surrogate_key(['YEAR', 'MONTH', 'PLATFORM', 'ID', 'EXAMPLE_ID', 'IS_MOBILE']) }} as id
    , *
FROM monthly_purchases
```
Here is the command I ran: `sqlfluff fix test.sql`
Important Notes:
- I was able to resolve this issue by making the dbt_utils.surrogate_key line shorter, see below:
{{ dbt_utils.surrogate_key(
[
'YEAR', 
'MONTH',
 'PLATFORM',
 'ID', 
'EXAMPLE_ID',
 'IS_MOBILE'
]
) }} as id

### Dialect

Snowflake

### Version

sqlfluff, version 2.3.3
Python 3.8.16
sqlfluff-templater-dbt 2.3.3
dbt core: 1.2.0
dbt snowflake: 1.2.0

### Configuration

[sqlfluff]
templater = dbt
dialect = snowflake

[sqlfluff:templater:dbt]
project_dir = .
profiles_dir = .
profile = gametime_snowflake

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by mauro-lanza** [comment]
Can confirm that this also happens to other rules like LT02 and LT08 .
Manually changing the file to add the expected indentation or new lines works and the parsing error disappears.

```
==== finding fixable violations ====
WARNING    Fixes for LT02 not applied, as it would result in an unparsable file. Please report this as a bug with a minimal query which demonstrates this warning.                    
WARNING    Fixes for LT08 not applied, as it would result in an unparsable file. Please report this as a bug with a minimal query which demonstrates this warning.  
```

sqlfluff, version >=2.3.3

[sqlfluff]
dialect = sparksql
templater = jinja

**Comment by alanmcruickshank** [comment]
@coleheflin-gt & @mauro-lanza - I'm having trouble recreating this issue. I've tried several versions of `dbt-snowflake` and several versions of `dbt-utils` on sqlfluff 2.3.3 and 2.3.4. Would you be able to help provide some more information so I can work out what's going on?

- Could you confirm that this issue is still present on SQLFluff 2.3.4 (the most recent SQLFluff version)? If it was in 2.3.3 then I will assume it _is_ but confirmation would be helpful because we did solve a similar bug recently (#5335).
- From your query, I'm assuming you're on an older version of `dbt_utils` (because `dbt_utils.surrogate_key` doesn't exist post 1.0.0, it's now `dbt_utils.generate_surrogate_key`). I tested your query against 0.9.6 and couldn't recreate the issue. Could you confirm the version of `dbt_utils` you're using in your `packages.yml` file?
- To the extent possible, if you're able to test with a more recent version of `dbt` or `dbt_utils` that would also help, but I understand if that's not possible in your environment. In particular, confirmation that this issue is still present with `dbt_utils >= 1.0.0` would be especially helpful, which would also require `dbt-core>=1.3.0`

Thanks also for pasting a cut-down version of your config file - that's extremely helpful if this issue is present on the default config - but if you could double check that this isn't dependent on any specific layout config in your project that might also help me recreate this.

If all else fails, could you save the logs from running `sqlfluff fix test.sql --logger rules -vvvvvv -r LT01`, which should only apply LT01 and only output logs from the rules logger. That will be harder to debug, but would give me a clue on what's happening here. @mauro-lanza - if you're experiencing this with `LT02` & `LT08`, then change the `-r` argument accordingly. If you're able to recreate a query which fails using `LT08` that would be especially interesting, because I expect the logs will be much quieter than the noisier rules like `LT01` or `LT02`.

**Comment by mauro-lanza** [comment]
@alanmcruickshank I can confirm the issue is both present in 2.3.3 and 2.3.4
Ill send you everything i have here so you can try to debug, it seem pretty weird since it recognizes the issue but something stops it from executing. If you need the query or anything else just tag me and ill try to respond as soon as possible. In my case i think the dbt-core and utils version in the env shouldn't  affect since the templater is sparksql.

.sqlfluff
```
[sqlfluff]
dialect = sparksql
templater = jinja
max_line_length = 0
exclude_rules = ST06
fix_even_unparsable = true

[sqlfluff:indentation]
allow_implicit_indents = True
indented_on_contents = False
indented_ctes = True

[sqlfluff:layout:type:alias_expression]
# We want non-default spacing _before_ the alias expressions.
spacing_before = align
# We want to align them within the next outer select clause.
# This means for example that alias expressions within the FROM
# or JOIN clause would _not_ be aligned with them.
align_within = select_clause
# The point at which to stop searching outward for siblings, which
# in this example would likely be the boundary of a CTE. Stopping
# when we hit brackets is usually a good rule of thumb for this
# configuration.
align_scope = bracketed

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper
[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = upper
[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper
[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper
[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper
```


Log for the rule LT08:

```
(venv) ➜  partner_ads git:(main) ✗ sqlfluff --version                                                                            
sqlfluff, version 2.3.4
(venv) ➜  partner_ads git:(main) ✗ sqlfluff fix src/dbt_project/models/odp/billing_central_invoices.sql --logger rules -vvvvvv -r LT08
==== sqlfluff ====
sqlfluff:                2.3.4 python:                 3.9.18
implementation:        cpython verbosity:                   6
dialect:              sparksql templater:               jinja
rules:                               LT08
== Raw Config:
core:                                   
    dialect:            sparksql            
    disable_noqa:       False               
    encoding:           autodetect          
    exclude_rules:      ST06                
    fix_even_unparsable:True                
    ignore:             []                  
    ignore_templated_areas:True                
    large_file_skip_byte_limit:20000               
    large_file_skip_char_limit:0                   
    max_line_length:    0                   
    nocolor:            False               
    output_line_length: 80                  
    processes:          1                   
    rules:              LT08                
    runaway_limit:      10                  
    sql_file_exts:      .sql,.sql.j2,.dml,.ddl
    templater:          jinja               
    verbose:            6                   
    warn_unused_ignores:False               
    warnings:           []                  
indentation:                            
    allow_implicit_indents:True                
    indent_unit:        space               
    indented_ctes:      True                
    indented_joins:     False               
    indented_on_contents:False               
    indented_then:      True                
    indented_then_contents:True                
    indented_using_on:  True                
    skip_indentation_in:script_content      
    tab_space_size:     4                   
    template_blocks_indent:True                
    trailing_comments:  before              
layout:                                 
    type:                                   
        alias_expression:                       
            align_scope:        bracketed           
            align_within:       select_clause       
            spacing_before:     align               
        array_accessor:                         
            spacing_before:     touch:inline        
        array_type:                             
            spacing_within:     touch:inline        
        assignment_operator:                    
            line_position:      leading             
            spacing_within:     touch               
        binary_operator:                        
            line_position:      leading             
            spacing_within:     touch               
        bracketed_arguments:                    
            spacing_before:     touch:inline        
        casting_operator:                       
            spacing_after:      touch:inline        
            spacing_before:     touch               
        colon:                                  
            spacing_before:     touch               
        colon_delimiter:                        
            spacing_after:      touch               
            spacing_before:     touch               
        comma:                                  
            line_position:      trailing            
            spacing_before:     touch               
        comment:                                
            spacing_after:      any                 
            spacing_before:     any                 
        common_table_expression:                    
            spacing_within:     single:inline       
        comparison_operator:                    
            line_position:      leading             
            spacing_within:     touch               
        dot:                                    
            spacing_after:      touch               
            spacing_before:     touch               
        end_angle_bracket:                      
            spacing_before:     touch               
        end_bracket:                            
            spacing_before:     touch               
        end_of_file:                            
            spacing_before:     touch               
        end_square_bracket:                     
            spacing_before:     touch               
        from_clause:                            
            line_position:      alone               
        function_name:                          
            spacing_after:      touch:inline        
            spacing_within:     touch:inline        
        groupby_clause:                         
            line_position:      alone               
        having_clause:                          
            line_position:      alone               
        join_clause:                            
            line_position:      alone               
        limit_clause:                           
            line_position:      alone               
        numeric_literal:                        
            spacing_within:     touch:inline        
        object_reference:                       
            spacing_within:     touch:inline        
        orderby_clause:                         
            line_position:      leading             
        path_segment:                           
            spacing_within:     touch               
        pattern_expression:                     
            spacing_within:     any                 
        placeholder:                            
            spacing_after:      any                 
            spacing_before:     any                 
        select_clause:                          
            line_position:      alone               
        semi_structured_expression:                    
            spacing_before:     touch:inline        
            spacing_within:     touch:inline        
        set_operator:                           
            line_position:      alone:strict        
        sign_indicator:                         
            spacing_after:      touch:inline        
        sized_array_type:                       
            spacing_within:     touch               
        slice:                                  
            spacing_after:      touch               
            spacing_before:     touch               
        sql_conf_option:                        
            spacing_within:     touch               
        sqlcmd_operator:                        
            spacing_before:     touch               
        start_angle_bracket:                    
            spacing_after:      touch               
        start_bracket:                          
            spacing_after:      touch               
        start_square_bracket:                    
            spacing_after:      touch               
        statement_terminator:                    
            line_position:      trailing            
            spacing_before:     touch               
        struct_type:                            
            spacing_within:     touch:inline        
        template_loop:                          
            spacing_after:      any                 
            spacing_before:     any                 
        tilde:                                  
            spacing_after:      touch:inline        
        typed_array_literal:                    
            spacing_within:     touch               
        typed_struct_literal:                    
            spacing_within:     touch               
        where_clause:                           
            line_position:      alone               
rules:                                  
    allow_scalar:       True                
    single_table_references:consistent          
    unquoted_identifiers_policy:all                 
    aliasing.column:                        
        aliasing:           explicit            
    aliasing.forbid:                        
        force_enable:       False               
    aliasing.length:                        
    aliasing.table:                         
        aliasing:           explicit            
    ambiguous.column_references:                    
        group_by_and_order_by_style:consistent          
    ambiguous.join:                         
        fully_qualify_join_types:inner               
    capitalisation.functions:                    
        extended_capitalisation_policy:upper               
    capitalisation.identifiers:                    
        capitalisation_policy:upper               
        extended_capitalisation_policy:consistent          
    capitalisation.keywords:                    
        capitalisation_policy:upper               
    capitalisation.literals:                    
        capitalisation_policy:upper               
    capitalisation.types:                    
        extended_capitalisation_policy:upper               
    convention.blocked_words:                    
        match_source:       False               
    convention.casting_style:                    
        preferred_type_casting_style:consistent          
    convention.count_rows:                    
        prefer_count_0:     False               
        prefer_count_1:     False               
    convention.quoted_literals:                    
        force_enable:       False               
        preferred_quoted_literal_style:consistent          
    convention.select_trailing_comma:                    
        select_clause_trailing_comma:forbid              
    convention.terminator:                    
        multiline_newline:  False               
        require_final_semicolon:False               
    layout.long_lines:                      
        ignore_comment_clauses:False               
        ignore_comment_lines:False               
    layout.select_targets:                    
        wildcard_policy:    single              
    references.consistent:                    
        force_enable:       False               
    references.from:                        
        force_enable:       False               
    references.keywords:                    
        unquoted_identifiers_policy:aliases             
    references.qualification:                    
    references.quoting:                     
        force_enable:       False               
        prefer_quoted_identifiers:False               
        prefer_quoted_keywords:False               
    references.special_chars:                    
        allow_space_in_identifier:False               
        quoted_identifiers_policy:all                 
        unquoted_identifiers_policy:all                 
    structure.join_condition_order:                    
        preferred_first_table_in_join_clause:earlier             
    structure.subquery:                     
        forbid_subquery_in: join                
templater:                              
    unwrap_wrapped_queries:True                
    jinja:                                  
        apply_dbt_builtins: True                

==== finding fixable violations ====
== [src/dbt_project/models/odp/billing_central_invoices.sql] LINTING (LT08)                                                                                                                                                                                                 
INFO       [LT08] ## CTE closing bracket found at [L:  8, P: 41], idx: 7. Forward slice: "(\n          SELECT                                                                                                                                                               
INFO       [LT08] blank_lines: 0, comma_line_idx: 0. final_line_idx: 1, final_seg_idx: 4                                                                                                                                                                                    
INFO       [LT08] comma_style: 'trailing', line_starts: {1: 3}, comment_lines: []                                                                                                                                                                                           
INFO       [LT08] !! Found CTE without enough blank lines.                                                                                                                                                                                                                  
INFO       [LT08] Comment routines not applicable                                                                                                                                                                                                                           
INFO       [LT08] ## CTE closing bracket found at [L: 12, P: 29], idx: 15. Forward slice: "(\n          SELECT                                                                                                                                                              
INFO       [LT08] blank_lines: 0, comma_line_idx: 0. final_line_idx: 1, final_seg_idx: 4                                                                                                                                                                                    
INFO       [LT08] comma_style: 'trailing', line_starts: {1: 3}, comment_lines: []                                                                                                                                                                                           
INFO       [LT08] !! Found CTE without enough blank lines.                                                                                                                                                                                                                  
INFO       [LT08] Comment routines not applicable                                                                                                                                                                                                                           
INFO       [LT08] ## CTE closing bracket found at [L: 17, P: 45], idx: 23. Forward slice: '(\n          SELECT                                                                                                                                                              
INFO       [LT08] blank_lines: 0, comma_line_idx: 0. final_line_idx: 1, final_seg_idx: 4                                                                                                                                                                                    
INFO       [LT08] comma_style: 'trailing', line_starts: {1: 3}, comment_lines: []                                                                                                                                                                                           
INFO       [LT08] !! Found CTE without enough blank lines.                                                                                                                                                                                                                  
INFO       [LT08] Comment routines not applicable                                                                                                                                                                                                                           
INFO       [LT08] ## CTE closing bracket found at [L: 27, P: 36], idx: 31. Forward slice: '(\n          SELECT                                                                                                                                                              
INFO       [LT08] blank_lines: 1, comma_line_idx: None. final_line_idx: 2, final_seg_idx: 4                                                                                                                                                                                 
INFO       [LT08] comma_style: 'final', line_starts: {1: 2, 2: 3}, comment_lines: []                                                                                                                                                                                        
INFO       [LT08] !! Violation Found: 'Blank line expected but not found after CTE closing bracket.'                                                                                                                                                                        
INFO       [LT08] !! Violation Found: 'Blank line expected but not found after CTE closing bracket.'                                                                                                                                                                        
INFO       [LT08] !! Violation Found: 'Blank line expected but not found after CTE closing bracket.'                                                                                                                                                                        
INFO       [LT08] !! Fix Proposed: <LintFix: replace whitespace@[L: 12, P:  1] edt:'       '->'\n'>                                                                                                                                                                         
INFO       [LT08] !! Fix Proposed: <LintFix: replace whitespace@[L: 17, P:  1] edt:'       '->'\n'>                                                                                                                                                                         
INFO       [LT08] !! Fix Proposed: <LintFix: replace whitespace@[L: 27, P:  1] edt:'       '->'\n'>                                                                                                                                                                         
rule LT08:   0%|                                                                                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]Fixes for LT08 not applied, as it would result in an unparsable file. Please report this as a bug with a minimal query which demonstrates this warning.
== [src/dbt_project/models/odp/billing_central_invoices.sql] FAIL                                                                                                                                                                                                           
L:  12 | P:   8 | LT08 | Blank line expected but not found after CTE closing
                       | bracket. [layout.cte_newline]
L:  17 | P:   8 | LT08 | Blank line expected but not found after CTE closing
                       | bracket. [layout.cte_newline]
L:  27 | P:   8 | LT08 | Blank line expected but not found after CTE closing
                       | bracket. [layout.cte_newline]
==== fixing violations ====
3 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
== [src/dbt_project/models/odp/billing_central_invoices.sql] FAIL
Done. Some operations failed. Please check your files to confirm.
Some errors cannot be fixed or there is another error blocking it.
```

**Comment by alanmcruickshank** [comment]
Thanks for the debug log, I think I can see what you're getting at. Is the issue here that the final linting step here fails? (i.e. the bit that says: `Some errors cannot be fixed or there is another error blocking it.`).

I thought initially the issue was the `WARNING` comments at the top: `WARNING    Fixes for LT08 not applied, as ...`.

For the failed fix application could you share the sql script (ideally exactly the same SQL file that generated the debug log above)? I think you're right that it shouldn't matter what database connection you're using. From what I can see here, as there are only three errors, and they don't overlap, there must be some issue in the _targetting_ of the fixes - meaning that one or more of them is unable to be applied because of some conflict with positioning in the source file.

My guess is that you're using some `jinja` templating, and something about the way that LT08 handles templated whitespace isn't being applied properly.

**Comment by mauro-lanza** [comment]
Sure, here is an example query that triggers the issues, if you try to format it with the configs i initially shared you are also going to notice that regardless of those errors nothing is being correctly formatted. 

```sql
{{
    config(
        materialized='table',
    )
}}


  WITH campaign_perf       AS (
          SELECT *
            FROM {{ source('source_odp','campaign_perf') }}
  ),
       campaign                   AS (
          SELECT *
            FROM {{ source('source_odp','campaign') }}
            WHERE billing = 'OTHER'
  ),
       campaign_perf_agg   AS (
          SELECT adserver_campaign_id,
                 report_date,
                 CAST(COALESCE(SUM(spent_local_currency), 0) AS DECIMAL(16, 8)) AS amount_local_currency,
                 CAST(COALESCE(SUM(spent_eur), 0) AS DECIMAL(16, 8))            AS amount_eur
            FROM campaign_perf
            GROUP BY 1, 2
            HAVING amount_local_currency > 0
  ),
       billing_central_invoices            AS (
          SELECT cp.campaign_id,
                 cp.adserver_campaign_id,
                 cp.creation_datetime,
                 CAST(cp.start_datetime AS DATE) AS start_date,
                 CAST(cp.end_datetime   AS DATE) AS end_date,
                 cp.country_code,
                 cp.city_code,
                 cp.currency_code,
                 cp.store_id,
                 cp.billing,
                 cpp.report_date,
                 cpp.amount_local_currency,
                 cpp.amount_eur
            FROM campaign_perf_agg     AS cpp
              INNER JOIN campaign              AS cp
                      ON cp.adserver_campaign_id = cpp.adserver_campaign_id
  )

SELECT /*+ REPARTITION(1) */ *
  FROM billing_central_invoices

```

**Comment by mauro-lanza** [comment]
@alanmcruickshank  Also as a side not i have noticed that some segments have intrinsic requirements and don't know if that is indeed the idea,
example:

- LateralViewClauseSegment must be written just below a FROM clause, when moving it to after some joins it gets parsing error
- ClusterByClauseSegment must have a FROM clause in the query for it to be valid so something like below would also cause errors:
```sql
select CURRENT_DATE() as p_data_date
cluster by p_data_date
```
Is this intended or should i raise an issue?

**Comment by alanmcruickshank** [comment]
> Is this intended or should i raise an issue?

If they're parsing fails, but are still valid queries - add them as new issues and that way someone will be able to pick them up while we focus on the formatting issues here.

**Comment by alanmcruickshank** [comment]
@mauro-lanza - I've found the issue with the errors you were seeing. It's a SparkSQL specific bug relating to the parsing (and re-parsing of) hints (the `/*+ REPARTITION(1) */` section wasn't successfully reparsing properly). I've got a fix which I think is ready to go, I'm just seeing whether I can use the intel from your issue to find the issue in the OP issue.

**Comment by coleheflin-gt** [comment]
@alanmcruickshank Apologies for the late response, work has been busy. See below for the answers to your questions:

1. I upgraded to the latest SQLFLUFF version and the same issue occurred as specified in my first post.
2. You're right, we are using an old verison of dbt_utils: 0.8.6
3. This change would likely affect our production environment and we don't currently have the time to upgrade and troubleshoot so unfortunately this is not an option at the moment.

See below for the output of this command: `sqlfluff fix test.sql --logger rules -vvvvvv -r LT01 --dialect=snowflake --templater=dbt`
```
==== sqlfluff ====
sqlfluff:                2.3.4 python:                 3.8.16
implementation:        cpython verbosity:                   6
dialect:             snowflake templater:                 dbt
dbt:                    =1.2.0
rules:                               LT01
== Raw Config:
core:
    dialect:            snowflake
    disable_noqa:       False
    encoding:           autodetect
    fix_even_unparsable:False
    ignore:             []
    ignore_templated_areas:True
    large_file_skip_byte_limit:20000
    large_file_skip_char_limit:0
    max_line_length:    80
    nocolor:            False
    output_line_length: 80
    processes:          1
    rules:              LT01
    runaway_limit:      10
    sql_file_exts:      .sql,.sql.j2,.dml,.ddl
    templater:          dbt
    verbose:            6
    warn_unused_ignores:False
    warnings:           []
indentation:
    allow_implicit_indents:False
    indent_unit:        space
    indented_ctes:      False
    indented_joins:     False
    indented_on_contents:True
    indented_then:      True
    indented_then_contents:True
    indented_using_on:  True
    skip_indentation_in:script_content
    tab_space_size:     4
    template_blocks_indent:True
    trailing_comments:  before
layout:
    type:
        array_accessor:
            spacing_before:     touch:inline
        array_type:
            spacing_within:     touch:inline
        assignment_operator:
            line_position:      leading
            spacing_within:     touch
        binary_operator:
            line_position:      leading
            spacing_within:     touch
        bracketed_arguments:
            spacing_before:     touch:inline
        casting_operator:
            spacing_after:      touch:inline
            spacing_before:     touch
        colon:
            spacing_before:     touch
        colon_delimiter:
            spacing_after:      touch
            spacing_before:     touch
        comma:
            line_position:      trailing
            spacing_before:     touch
        comment:
            spacing_after:      any
            spacing_before:     any
        common_table_expression:
            spacing_within:     single:inline
        comparison_operator:
            line_position:      leading
            spacing_within:     touch
        dot:
            spacing_after:      touch
            spacing_before:     touch
        end_angle_bracket:
            spacing_before:     touch
        end_bracket:
            spacing_before:     touch
        end_of_file:
            spacing_before:     touch
        end_square_bracket:
            spacing_before:     touch
        from_clause:
            line_position:      alone
        function_name:
            spacing_after:      touch:inline
            spacing_within:     touch:inline
        groupby_clause:
            line_position:      alone
        having_clause:
            line_position:      alone
        join_clause:
            line_position:      alone
        limit_clause:
            line_position:      alone
        numeric_literal:
            spacing_within:     touch:inline
        object_reference:
            spacing_within:     touch:inline
        orderby_clause:
            line_position:      leading
        path_segment:
            spacing_within:     touch
        pattern_expression:
            spacing_within:     any
        placeholder:
            spacing_after:      any
            spacing_before:     any
        select_clause:
            line_position:      alone
        semi_structured_expression:
            spacing_before:     touch:inline
            spacing_within:     touch:inline
        set_operator:
            line_position:      alone:strict
        sign_indicator:
            spacing_after:      touch:inline
        sized_array_type:
            spacing_within:     touch
        slice:
            spacing_after:      touch
            spacing_before:     touch
        sql_conf_option:
            spacing_within:     touch
        sqlcmd_operator:
            spacing_before:     touch
        start_angle_bracket:
            spacing_after:      touch
        start_bracket:
            spacing_after:      touch
        start_square_bracket:
            spacing_after:      touch
        statement_terminator:
            line_position:      trailing
            spacing_before:     touch
        struct_type:
            spacing_within:     touch:inline
        template_loop:
            spacing_after:      any
            spacing_before:     any
        tilde:
            spacing_after:      touch:inline
        typed_array_literal:
            spacing_within:     touch
        typed_struct_literal:
            spacing_within:     touch
        where_clause:
            line_position:      alone
rules:
    allow_scalar:       True
    single_table_references:consistent
    unquoted_identifiers_policy:all
    aliasing.column:
        aliasing:           explicit
    aliasing.forbid:
        force_enable:       False
    aliasing.length:
    aliasing.table:
        aliasing:           explicit
    ambiguous.column_references:
        group_by_and_order_by_style:consistent
    ambiguous.join:
        fully_qualify_join_types:inner
    capitalisation.functions:
        extended_capitalisation_policy:consistent
    capitalisation.identifiers:
        extended_capitalisation_policy:consistent
    capitalisation.keywords:
        capitalisation_policy:consistent
    capitalisation.literals:
        capitalisation_policy:consistent
    capitalisation.types:
        extended_capitalisation_policy:consistent
    convention.blocked_words:
        match_source:       False
    convention.casting_style:
        preferred_type_casting_style:consistent
    convention.count_rows:
        prefer_count_0:     False
        prefer_count_1:     False
    convention.quoted_literals:
        force_enable:       False
        preferred_quoted_literal_style:consistent
    convention.select_trailing_comma:
        select_clause_trailing_comma:forbid
    convention.terminator:
        multiline_newline:  False
        require_final_semicolon:False
    layout.long_lines:
        ignore_comment_clauses:False
        ignore_comment_lines:False
    layout.select_targets:
        wildcard_policy:    single
    references.consistent:
        force_enable:       False
    references.from:
        force_enable:       False
    references.keywords:
        unquoted_identifiers_policy:aliases
    references.qualification:
    references.quoting:
        force_enable:       False
        prefer_quoted_identifiers:False
        prefer_quoted_keywords:False
    references.special_chars:
        allow_space_in_identifier:False
        quoted_identifiers_policy:all
        unquoted_identifiers_policy:all
    structure.join_condition_order:
        preferred_first_table_in_join_clause:earlier
    structure.subquery:
        forbid_subquery_in: join
templater:
    unwrap_wrapped_queries:True
    dbt:
        profile:            gametime_snowflake
        profiles_dir:       /Users/coleheflin/Repos/airflow/dbt_snowflake/.
        project_dir:        /Users/coleheflin/Repos/airflow/dbt_snowflake/.
    jinja:
        apply_dbt_builtins: True

==== finding fixable violations ====
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/de_core/events/rollups/events__monthly_purchases.sql] LINTING (LT01)
DEBUG      * Respacing: '\n\n' @ [L:  7, P:  3]
DEBUG      * Respacing: ' ' @ [L:  9, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L:  9, P: 23]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L:  9, P: 26]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n    ' @ [L:  9, P: 28]
DEBUG      * Respacing: '\n        ' @ [L: 10, P: 11]
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 11, P: 14]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 11, P: 20]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 11, P: 21]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 11, P: 24]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 11, P: 29]
DEBUG      * Respacing: ' ' @ [L: 12, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 12, P: 17]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 12, P: 23]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 12, P: 24]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 12, P: 27]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 12, P: 33]
DEBUG      * Respacing: ' ' @ [L: 13, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 13, P: 19]
DEBUG      * Respacing: ' ' @ [L: 14, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 14, P: 13]
DEBUG      * Respacing: ' ' @ [L: 15, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 15, P: 21]
DEBUG      * Respacing: ' ' @ [L: 16, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 16, P: 20]
DEBUG      * Respacing: ' ' @ [L: 17, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 17, P: 15]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 19]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 24]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 35]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 37]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 48]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 53]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 55]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 60]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 62]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 17, P: 66]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 17, P: 67]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 17, P: 70]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n        ' @ [L: 17, P: 84]
DEBUG      * Respacing: '\n    ' @ [L: 18, P: 78]
DEBUG      * Respacing: ' ' @ [L: 19, P:  9]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 19, P: 51]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n    ' @ [L: 19, P: 56]
DEBUG      * Respacing: '' @ [L: 20, P: 30]
DEBUG          Inline case. Constraints: any <-> any.
DEBUG      * Respacing: '' @ [L: 22, P:  5]
DEBUG          Inline case. Constraints: any <-> any.
DEBUG      * Respacing: '\n    ' @ [L: 22, P: 16]
DEBUG      * Respacing: ' ' @ [L: 23, P: 10]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 23, P: 13]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n' @ [L: 23, P: 17]
DEBUG      * Respacing: '\n' @ [L: 24, P:  2]
DEBUG      * Respacing: '\n    ' @ [L: 25, P:  7]
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: touch <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ None
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' \n    ' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '\n' @ [L: 26, P:  5]
DEBUG          Skipping templated newline: <NewlineSegment: ([L: 26, P:  5]) '\n'>
DEBUG      * Respacing: '' @ [L: 26, P:  5]
DEBUG          Inline case. Constraints: single <-> touch.
DEBUG      * Respacing: ' ' @ [L: 26, P: 98]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: ' ' @ [L: 26, P:101]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n    ' @ [L: 26, P:104]
DEBUG      * Respacing: ' ' @ [L: 27, P:  6]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '\n' @ [L: 27, P:  8]
DEBUG      * Respacing: ' ' @ [L: 28, P:  5]
DEBUG          Inline case. Constraints: single <-> single.
DEBUG      * Respacing: '' @ [L: 28, P: 23]
== [models/de_core/events/rollups/events__monthly_purchases.sql] PASS
==== no fixable linting violations found ====
All Finished 📜 🎉!
```

**Comment by alanmcruickshank** [comment]
> See below for the output of this command: `sqlfluff fix test.sql --logger rules -vvvvvv -r LT01 --dialect=snowflake --templater=dbt`

I'm a little confused, as that log output doesn't include the problem from the original issue. It looks like the file is passing the linting check and there aren't any `WARNING` lines any more from the original issue. Does this mean the issue is fixed on your side, or am I misunderstanding the issue that you're seeing?

**Comment by coleheflin-gt** [comment]
The issue was not resolved despite the log not showing any errors or warnings. When I ran the `sqlfluff fix test.sql` without the logger arguments specified above I received the same error as I mentioned at the beginning of this issue.

**Comment by alanmcruickshank** [comment]
Unfortunately I can't recreate it yet no 🤔 .

Perhaps I need to broaden my search a little, try running `sqlfluff fix test.sql --logger linter -vvvvvv  --dialect=snowflake --templater=dbt`. I hope with this version you still see the `WARNING` lines, but you should also got some more information on whey they're being caused. If you can paste the logs here from that, I'm hoping it should provide some more detail.
